task:
    environment: default
    fieldgrid:
        children:
        -   id: element_0
            w: 4
            x: 0
            y: 0
        -   id: element_9
            w: 12
            x: 0
            y: 1
        -   id: element_8
            w: 12
            x: 0
            y: 2
        -   h: 10
            id: element_7
            w: 12
            x: 0
            y: 3
        elements:
            element_0:
                text: 'Path: '
            element_7:
                url: ./../Fields/Description.field.yaml
            element_8:
                url: ./../Fields/User Priority.field.yaml
            element_9:
                url: ./../Fields/Type.field.yaml
        values:
            description: hi
            local_slates_issues_tasks_add_issues_task_yaml_element_0: 'Path: '
            type: null
            user_priority: null
    streams:
    -   main:
        -   content: "from datetime import datetime\nimport uuid\n\n# generate unique\
                \ issue_id and get current timestamp\nissue_id = str(uuid.uuid4())\n\
                now = datetime.now().isoformat()\nusername = user['username']\n\n\
                if 'description' in parameters:\n    desc = parameters['description'].strip().replace(\"\
                '\", \"''\")  # escape single quotes\n\nurl=parameters.get(\"original_url\"\
                ,\"no url\")\n\n# if 'original_url' in parameters:\n#     url = parameters['original_url']\n\
                #     print(\"parameters: \" + url)\n# else:\n#     url = \"\"\n#\
                \     print(\"no url parameter\")"
            loop-iterable: ''
            type: code
        -   chart:
                advanced: ''
                legend: 'Off'
                series-annos:
                -   anno-col: ''
                    anno-col-back: ''
                    anno-dt: false
                    anno-label: ''
                    anno-s: ''
                    anno-tab: 0
                    anno-type: box
                    anno-u: ''
                    anno-width: ''
                    anno-x: ''
                    anno-xm: ''
                    anno-y: ''
                    anno-ym: ''
                series-formats:
                -   format-col: ''
                    format-col-back: ''
                    format-dt: false
                    format-f: false
                    format-lw: ''
                    format-nrx: ''
                    format-p: false
                    format-pr: ''
                    format-ps: circle
                    format-title: ''
                    format-ua: ''
                series-groups:
                -   series-l: ''
                    series-s: ''
                    series-tab: 0
                    series-type: Line
                    series-u: ''
                    series-x: ''
                    series-y: ''
                    series-ymax: ''
                    series-ymin: ''
                    series-z: ''
                subtitle: ''
                title: ''
                xaxis-type: category
            loop-iterable: ''
            output: table
            table:
                checkbox: false
                export: false
                filter: false
                footer: false
                multiselect-row: false
                pagesize: '15'
                pagination: true
                search: false
                sortable: true
                style: default
                title: ''
            tabs:
            -   content: 'INSERT INTO issues (issue_id, "type", user_priority, description,
                    path, "user", status, date_created, date_updated)

                    VALUES (''{issue_id}'', ''{parameters["type"]}'', ''{parameters["user_priority"]}'',
                    ''{desc}'', ''{url}'', ''{username}'', ''Created'', ''{ now }'',
                    ''{ now }'');

                    COMMIT;'
                source: '{ Clarama[''Services''][''ClaramaSourceDB''] }'
                tab_id: 0
            type: data
