task:
    environment: default
    fieldgrid:
        children:
        -   id: element_2
            w: 4
            x: 0
            y: 0
        elements:
            element_0:
                url: ./Add_Comments.task.yaml
            element_1:
                url: ./../Fields/issues/Comment.field.yaml
            element_2:
                url: ./../Tables/comments fields/issue_id.field.yaml
        values:
            issue_id: ''
    streams:
    -   main:
        -   content: "filters = []\n\nrun = False\nif 'issue_id' in parameters:\n\
                \    issue_id = parameters['issue_id']\n    \n    if issue_id != \"\
                \":\n        print(\"issue_id: \" + issue_id)\n        filters.append(f\"\
                \"\"issue_id = '{issue_id}'\"\"\")\n        run = True\n\nfilter=\"\
                \"\n\nif len(filters)>0:\n    filter = 'WHERE ' + ' AND '.join(filters)\n\
                \nprint(\"Filter:\", filter)"
            loop-iterable: ''
            type: code
        -   chart:
                advanced: ''
                legend: 'Off'
                series-annos:
                -   anno-col: ''
                    anno-col-back: ''
                    anno-dt: false
                    anno-i: ''
                    anno-label: ''
                    anno-s: ''
                    anno-tab: 0
                    anno-type: box
                    anno-u: ''
                    anno-width: ''
                    anno-x: ''
                    anno-xm: ''
                    anno-y: ''
                    anno-ym: ''
                series-formats:
                -   format-col: ''
                    format-col-back: ''
                    format-dt: false
                    format-f: false
                    format-lw: ''
                    format-nrx: ''
                    format-p: false
                    format-pr: ''
                    format-ps: circle
                    format-title: ''
                    format-ua: ''
                series-groups:
                -   series-l: ''
                    series-s: ''
                    series-tab: 0
                    series-type: Line
                    series-u: ''
                    series-x: ''
                    series-y: ''
                    series-ymax: ''
                    series-ymin: ''
                    series-z: ''
                subtitle: ''
                title: ''
                xaxis-type: category
            loop-iterable: run
            output: table
            table:
                checkbox: true
                export: false
                filter: false
                footer: false
                multiselect-row: false
                pagesize: '15'
                pagination: true
                search: true
                slate: ''
                sortable: true
                style: default
                title: ''
            tabs:
            -   content: 'select comment_id, issue_id, reviewer, comment, date_created

                    from comments

                    {filter}

                    ORDER BY date_created DESC

                    LIMIT 3;'
                source: '{ Clarama[''Services''][''ClaramaSourceDB''] }'
                tab_id: 0
            type: data
