task:
    environment: native_shared.environment.yaml
    fieldgrid:
        children:
        -   id: element_0
            w: 12
            x: 0
            y: 0
        elements:
            element_0:
                spacing: '1'
                url: ./../Tables/comments fields/comment_id.field.yaml
        values:
            comment_id: ''
    streams:
    -   main:
        -   content: ''
            loop-iterable: ''
            type: code
        -   chart:
                advanced: ''
                legend: 'Off'
                series-annos:
                -   anno-col: ''
                    anno-col-back: ''
                    anno-dt: false
                    anno-i: ''
                    anno-label: ''
                    anno-s: ''
                    anno-tab: 0
                    anno-type: box
                    anno-u: ''
                    anno-width: ''
                    anno-x: ''
                    anno-xm: ''
                    anno-y: ''
                    anno-ym: ''
                series-formats:
                -   format-col: ''
                    format-col-back: ''
                    format-dt: false
                    format-f: false
                    format-lw: ''
                    format-nrx: ''
                    format-p: false
                    format-pr: ''
                    format-ps: circle
                    format-title: ''
                    format-ua: ''
                series-groups:
                -   series-l: ''
                    series-s: ''
                    series-tab: 0
                    series-type: Line
                    series-u: ''
                    series-x: ''
                    series-y: ''
                    series-ymax: ''
                    series-ymin: ''
                    series-z: ''
                subtitle: ''
                title: ''
                xaxis-type: category
            loop-iterable: ''
            output: table
            table:
                checkbox: false
                export: false
                filter: false
                footer: false
                multiselect-row: false
                pagesize: '15'
                pagination: true
                search: false
                slate: ''
                sortable: true
                style: default
                title: ''
            tabs:
            -   content: 'delete from comments

                    where comment_id = ''{parameters[''comment_id'']}'';

                    commit;'
                source: '{ Clarama[''Services''][''ClaramaSourceDB''] }'
                tab_id: 0
            type: data
        -   content: print(parameters)
            loop-iterable: ''
            type: code
