task:
    environment: default
    fieldgrid:
        children:
        -   id: element_0
            w: 6
            x: 0
            y: 0
        -   id: element_2
            w: 6
            x: 6
            y: 0
        -   id: element_9
            w: 6
            x: 0
            y: 1
        -   id: element_8
            w: 6
            x: 6
            y: 1
        -   h: 2
            id: element_1
            w: 6
            x: 0
            y: 2
        -   h: 2
            id: element_3
            w: 6
            x: 6
            y: 2
        -   h: 8
            id: element_7
            w: 12
            x: 0
            y: 4
        elements:
            element_0:
                text: 'Path: '
            element_1:
                spacing: '2'
                url: ./../Fields/Status.field.yaml
            element_2:
                spacing: '3'
                url: ./../Fields/issue_id.field.yaml
            element_3:
                url: ./../Fields/assigned_to.field.yaml
            element_7:
                spacing: '1'
                url: ./../Fields/Description.field.yaml
            element_8:
                url: ./../Fields/User Priority.field.yaml
            element_9:
                spacing: '2'
                url: ./../Fields/Type.field.yaml
        values:
            assigned_to: null
            description: hi
            issue_id: ''
            local_slates_issues_tasks_edit_issue_task_yaml_element_0: 'Path: '
            status: Open
            type: Issue
            user_priority: Low
    streams:
    -   main:
        -   content: "from datetime import datetime\nimport uuid\n\nnow = datetime.now().isoformat()\n\
                username = user['username']\n\nif 'issue_id' in parameters:\n    issue_id\
                \ = parameters['issue_id']\n        \n    if issue_id != \"\":\n \
                \       print(\"parameters: \" + issue_id)\n\nif 'description' in\
                \ parameters:\n    desc = parameters['description'].strip().replace(\"\
                '\", \"''\")  # escape single quotes"
            loop-iterable: ''
            type: code
        -   chart:
                advanced: ''
                legend: 'Off'
                series-annos:
                -   anno-col: ''
                    anno-col-back: ''
                    anno-dt: false
                    anno-i: ''
                    anno-label: ''
                    anno-s: ''
                    anno-tab: 0
                    anno-type: box
                    anno-u: ''
                    anno-width: ''
                    anno-x: ''
                    anno-xm: ''
                    anno-y: ''
                    anno-ym: ''
                series-formats:
                -   format-col: ''
                    format-col-back: ''
                    format-dt: false
                    format-f: false
                    format-lw: ''
                    format-nrx: ''
                    format-p: false
                    format-pr: ''
                    format-ps: circle
                    format-title: ''
                    format-ua: ''
                series-groups:
                -   series-l: ''
                    series-s: ''
                    series-tab: 0
                    series-type: Line
                    series-u: ''
                    series-x: ''
                    series-y: ''
                    series-ymax: ''
                    series-ymin: ''
                    series-z: ''
                subtitle: ''
                title: ''
                xaxis-type: category
            loop-iterable: ''
            output: table
            table:
                checkbox: false
                export: false
                filter: false
                footer: false
                multiselect-row: false
                pagesize: '15'
                pagination: true
                search: false
                slate: ''
                sortable: true
                style: default
                title: ''
            tabs:
            -   content: 'UPDATE issues

                    SET "type" = ''{parameters["type"]}'', user_priority = ''{parameters["user_priority"]}'',
                    description = ''{desc}'', status = ''{parameters["status"]}'',
                    date_updated = ''{now}''

                    WHERE issue_id = ''{issue_id}'';

                    COMMIT;'
                source: '{ Clarama[''Services''][''ClaramaSourceDB''] }'
                tab_id: 0
            type: data
