task:
    environment: default
    fieldgrid:
        children:
        -   h: 2
            id: element_0
            w: 10
            x: 0
            y: 0
        -   h: 2
            id: element_1
            w: 10
            x: 0
            y: 2
        -   id: element_2
            w: 10
            x: 0
            y: 4
        elements:
            element_0:
                url: ./../Fields/uuid.field.yaml
            element_1:
                url: ./../Fields/cron.field.yaml
            element_2:
                text: Edit the CRON settings, then press Play to save the results
        values:
            cron: ''
            system_plugins_slates_jobs_tasks_job_update_task_yaml_element_2: Edit
                the CRON settings, then press Play to save the results
            uuid: ''
    streams:
    -   main:
        -   content: "update=False\n\nif 'row' in parameters:\n    update=True"
            loop-iterable: ''
            type: code
        -   content: alert(parameters)
            loop-iterable: ''
            type: code
        -   chart:
                advanced: ''
                legend: 'Off'
                series-annos:
                -   anno-col: ''
                    anno-col-back: ''
                    anno-dt: false
                    anno-i: ''
                    anno-label: ''
                    anno-s: ''
                    anno-tab: 0
                    anno-type: box
                    anno-u: ''
                    anno-width: ''
                    anno-x: ''
                    anno-xm: ''
                    anno-y: ''
                    anno-ym: ''
                series-formats:
                -   format-col: ''
                    format-col-back: ''
                    format-dt: false
                    format-f: false
                    format-lw: ''
                    format-nrx: ''
                    format-p: false
                    format-pr: ''
                    format-ps: circle
                    format-title: ''
                    format-ua: ''
                series-groups:
                -   series-l: ''
                    series-s: ''
                    series-tab: 0
                    series-type: Line
                    series-u: ''
                    series-x: ''
                    series-y: ''
                    series-ymax: ''
                    series-ymin: ''
                    series-z: ''
                subtitle: ''
                title: ''
                xaxis-type: category
            loop-iterable: ''
            output: code
            table:
                checkbox: false
                export: false
                filter: false
                footer: false
                multiselect-row: false
                pagesize: '15'
                pagination: true
                search: false
                slate: ''
                sortable: true
                style: default
                title: ''
            tabs:
            -   content: "update jobs \nset cron='{parameters['cron']}' \nwhere uuid='{parameters['uuid']}';\n\
                    commit;\n"
                source: '{ Clarama[''Services''][''ClaramaSourceDB''] }'
                tab_id: 0
            type: data
        -   chart:
                advanced: ''
                legend: 'Off'
                series-annos:
                -   anno-col: ''
                    anno-col-back: ''
                    anno-dt: false
                    anno-i: ''
                    anno-label: ''
                    anno-s: ''
                    anno-tab: 0
                    anno-type: box
                    anno-u: ''
                    anno-width: ''
                    anno-x: ''
                    anno-xm: ''
                    anno-y: ''
                    anno-ym: ''
                series-formats:
                -   format-col: ''
                    format-col-back: ''
                    format-dt: false
                    format-f: false
                    format-lw: ''
                    format-nrx: ''
                    format-p: false
                    format-pr: ''
                    format-ps: circle
                    format-title: ''
                    format-ua: ''
                series-groups:
                -   series-l: ''
                    series-s: ''
                    series-tab: 0
                    series-type: Line
                    series-u: ''
                    series-x: ''
                    series-y: ''
                    series-ymax: ''
                    series-ymin: ''
                    series-z: ''
                subtitle: ''
                title: ''
                xaxis-type: category
            loop-iterable: ''
            output: table
            table:
                checkbox: false
                export: false
                filter: false
                footer: false
                multiselect-row: false
                pagesize: '15'
                pagination: true
                search: false
                slate: ''
                sortable: true
                style: default
                title: ''
            tabs:
            -   content: 'select uuid, cron from jobs

                    where uuid=''{parameters[''uuid'']}'''
                source: '{ Clarama[''Services''][''ClaramaSourceDB''] }'
                tab_id: 0
            type: data
